version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=80
    ports:
      - "3001:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - backend-network

networks:
  backend-network:
    external: true